version: '3'
services:
  speaker-manager:
    build:
      context: ./speaker-manager
      dockerfile: Dockerfile
    image: speaker-manager-image
    container_name: speaker-manager
    restart: unless-stopped
    #privileged: true
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /etc/machine-id:/etc/machine-id
      - ~/.config/pulse/cookie:/home/sneer/.config/pulse/cookie
      #- /usr/local/speakerManager/logs:/logs
    environment:
      - TZ=America/Costa_Rica
    network_mode: host